requireModuleInFile rootPath.services, 'service-base'
requireModuleInFile rootPath.services, 'user-service'
requireModuleInFile rootPath.services, 'geocode-service'
requireModuleInFile rootPath.services, 'craft-service'
requireModuleInFile rootPath.services, 'tweet-stream-service'
requireModuleInFile rootPath.services, 'halo-halo-service'
